use super::catalog::{
    ConfidencePolicy, Language, LanguageFinding, LanguageRule, Matcher, ProofWindow,
};
use super::common::{
    is_dev_only_path, is_docs_reference_tips_or_generated, nearby_allow, sort_and_cap_findings,
};
use crate::audit::helpers::AuditContext;
use crate::audit::scan;
use crate::model::FileInfo;
use once_cell::sync::Lazy;

const HLT_RULE_ID: &str = "HLT-041-COMMENT-HYGIENE";

#[derive(Debug, Clone, Copy, Default)]
pub struct CommentsSummary {
    pub hard_findings: usize,
    pub advisory_signals: usize,
}

pub fn summary(ctx: &AuditContext) -> CommentsSummary {
    CommentsSummary {
        hard_findings: findings(ctx).len(),
        advisory_signals: advisory_signals(ctx).len(),
    }
}

// ---------------------------------------------------------------------------
// Tier 1 — Hard block phrases (high confidence, blocking)
// These are compound phrases that inherently confess dangerous intent.
// Single words are NEVER used alone to avoid false positives.
// ---------------------------------------------------------------------------

const TIER1_SECURITY_BYPASS: &[&str] = &[
    "skip auth",
    "bypass auth",
    "disable auth",
    "skip authentication",
    "bypass authentication",
    "disable authentication",
    "skip authorization",
    "bypass authorization",
    "no permission check",
    "skip permission",
    "disable ssl",
    "disable tls",
    "skip ssl",
    "skip tls",
    "skip certificate",
    "skip validation",
    "disable validation",
    "trust all certificates",
    "allow all origins",
    "disable cors",
    "disable csrf",
    "skip csrf",
    "skip rate limit",
    "disable rate limit",
    "no rate limit",
    "disable security",
    "skip security",
    "security disabled",
];

const TIER1_PRODUCTION_CONFESSIONS: &[&str] = &[
    "remove before production",
    "delete before release",
    "remove before release",
    "remove before deploy",
    "not production ready",
    "not prod ready",
    "for testing only",
    "dev only",
    "will fix later",
    "fix later",
    "known vulnerability",
    "known security issue",
    "temporary workaround",
    "temporary fix",
    "temporary hack",
    "do not ship",
    "do not deploy",
    "not for production",
    "debug only",
];

const TIER1_HARDCODED_SECRETS: &[&str] = &[
    "hardcoded password",
    "hardcoded secret",
    "hardcoded token",
    "hardcoded key",
    "hardcoded credential",
    "hardcoded api key",
    "default password",
    "default secret",
    "default token",
    "password goes here",
    "secret goes here",
    "token goes here",
];

const TIER1_AI_RESIDUE: &[&str] = &[
    "generated by ai",
    "ai generated",
    "ai placeholder",
    "agent placeholder",
    "copilot suggested",
    "chatgpt wrote",
    "llm generated",
    "gpt generated",
    "claude generated",
    "ai wrote this",
    "auto-generated stub",
    "llm placeholder",
];

const TIER1_FAKE_IMPLEMENTATION: &[&str] = &[
    "fake implementation",
    "stub implementation",
    "mock in production",
    "dummy data in production",
    "placeholder logic",
    "not actually implemented",
    "noop implementation",
    "no-op implementation",
    "empty implementation",
    "returns hardcoded",
    "returns dummy",
    "pretend to",
];

const TIER1_ERROR_SUPPRESSION: &[&str] = &[
    "swallow exception",
    "swallow error",
    "ignore error",
    "ignore exception",
    "silence warning",
    "silence error",
    "suppress error",
    "suppress exception",
    "catch all exceptions",
    "empty catch",
    "intentionally swallowed",
    "deliberately ignored error",
    "eat the error",
    "discard error",
];

// All tier 1 phrase groups combined with their category tag.
static TIER1_ALL: Lazy<Vec<(&'static str, &'static str)>> = Lazy::new(|| {
    let mut v = Vec::new();
    for p in TIER1_SECURITY_BYPASS {
        v.push((*p, "security-bypass"));
    }
    for p in TIER1_PRODUCTION_CONFESSIONS {
        v.push((*p, "production-confession"));
    }
    for p in TIER1_HARDCODED_SECRETS {
        v.push((*p, "hardcoded-secret"));
    }
    for p in TIER1_AI_RESIDUE {
        v.push((*p, "ai-residue"));
    }
    for p in TIER1_FAKE_IMPLEMENTATION {
        v.push((*p, "fake-implementation"));
    }
    for p in TIER1_ERROR_SUPPRESSION {
        v.push((*p, "error-suppression"));
    }
    v
});

// ---------------------------------------------------------------------------
// Tier 2 — Advisory context pairs (medium confidence, non-blocking)
// These fire only when a marker word co-occurs with a security/safety noun
// in the same comment line.
// ---------------------------------------------------------------------------

const TIER2_MARKERS: &[&str] = &["todo", "fixme", "hack", "xxx", "workaround", "kludge"];

const TIER2_CONTEXT_NOUNS: &[&str] = &[
    "auth",
    "authentication",
    "authorization",
    "permission",
    "encrypt",
    "encryption",
    "decrypt",
    "certificate",
    "tls",
    "ssl",
    "credential",
    "password",
    "secret",
    "token",
    "injection",
    "sanitize",
    "sanitization",
    "validate",
    "validation",
    "xss",
    "csrf",
    "cors",
    "rate limit",
    "rate-limit",
    "timeout",
    "session",
    "privilege",
    "escalation",
    "rollback",
    "migration",
    "backup",
    "vulnerability",
    "exploit",
    "security",
];

// ---------------------------------------------------------------------------
// Comment extraction
// ---------------------------------------------------------------------------

/// Extensions that contain source code with scannable comments.
const CODE_EXTENSIONS: &[&str] = &[
    ".rs", ".ts", ".tsx", ".js", ".jsx", ".mts", ".cts", ".py", ".sh", ".bash", ".go", ".sql",
    ".c", ".cc", ".cpp", ".cs", ".java", ".kt", ".kts", ".rb", ".swift", ".scala", ".dart", ".ex",
    ".exs", ".lua", ".php",
];

/// Try to extract the comment portion of a source line.
/// Returns `Some(comment_text)` if the line contains a comment, `None` otherwise.
fn extract_comment(line: &str, ext: &str) -> Option<String> {
    let trimmed = line.trim();
    if trimmed.is_empty() {
        return None;
    }

    match ext {
        // C-family // and /* comments
        ".rs" | ".ts" | ".tsx" | ".js" | ".jsx" | ".mts" | ".cts" | ".go" | ".c" | ".cc"
        | ".cpp" | ".cs" | ".java" | ".kt" | ".kts" | ".swift" | ".scala" | ".dart" => {
            // Full-line comment
            if trimmed.starts_with("///") || trimmed.starts_with("//!") {
                return Some(trimmed[3..].to_string());
            }
            if let Some(stripped) = trimmed.strip_prefix("//") {
                return Some(stripped.to_string());
            }
            if trimmed.starts_with("/*") {
                let inner = trimmed.trim_start_matches("/*").trim_end_matches("*/");
                return Some(inner.to_string());
            }
            if trimmed.starts_with('*') && !trimmed.starts_with("*/") {
                // Inside a block comment continuation line
                return Some(trimmed[1..].to_string());
            }
            // Inline comment after code
            if let Some(pos) = line.find("//") {
                // Make sure it's not inside a string literal (basic heuristic:
                // count unescaped quotes before the // position)
                let before = &line[..pos];
                let double_quotes = before.chars().filter(|&c| c == '"').count();
                if double_quotes % 2 == 0 {
                    return Some(line[pos + 2..].to_string());
                }
            }
            None
        }
        // Hash comments
        ".py" | ".sh" | ".bash" | ".rb" | ".ex" | ".exs" | ".lua" | ".php" => {
            if let Some(stripped) = trimmed.strip_prefix('#') {
                return Some(stripped.to_string());
            }
            // Python/Ruby also support inline #
            if let Some(pos) = line.find('#') {
                let before = &line[..pos];
                let double_quotes = before.chars().filter(|&c| c == '"').count();
                let single_quotes = before.chars().filter(|&c| c == '\'').count();
                if double_quotes % 2 == 0 && single_quotes % 2 == 0 {
                    return Some(line[pos + 1..].to_string());
                }
            }
            None
        }
        // SQL: -- comments
        ".sql" => {
            if let Some(stripped) = trimmed.strip_prefix("--") {
                return Some(stripped.to_string());
            }
            if trimmed.starts_with("/*") {
                let inner = trimmed.trim_start_matches("/*").trim_end_matches("*/");
                return Some(inner.to_string());
            }
            if let Some(pos) = line.find("--") {
                let before = &line[..pos];
                let quotes = before.chars().filter(|&c| c == '\'').count();
                if quotes % 2 == 0 {
                    return Some(line[pos + 2..].to_string());
                }
            }
            None
        }
        _ => None,
    }
}

// ---------------------------------------------------------------------------
// File filtering
// ---------------------------------------------------------------------------

fn is_comment_scannable_file(file: &FileInfo) -> bool {
    // Must be a code file extension
    if !CODE_EXTENSIONS.contains(&file.suffix.as_str()) {
        return false;
    }
    // Exclude docs, reference, tips, generated, paper, target
    if is_docs_reference_tips_or_generated(&file.rel_path) {
        return false;
    }
    // Exclude tests, fixtures, examples
    if is_dev_only_path(&file.rel_path) {
        return false;
    }
    // Exclude generated/reference via scan helpers
    if scan::is_generated_or_reference_path(&file.rel_path) {
        return false;
    }
    // Exclude Jankurai's own crates (self-audit exclusion)
    let lower = file.rel_path.to_ascii_lowercase();
    if lower.starts_with("crates/jankurai/")
        || lower.starts_with("crates/jankurai-proofbind/")
        || lower.starts_with("crates/jankurai-proofmark/")
    {
        return false;
    }
    true
}

fn scannable_files(ctx: &AuditContext) -> Vec<&FileInfo> {
    let zone_paths = crate::audit::helpers::generated_zone_suppression_paths(ctx);
    ctx.all_files
        .iter()
        .filter(|file| {
            is_comment_scannable_file(file)
                && !zone_paths
                    .iter()
                    .any(|zone| crate::audit::helpers::path_matches_prefix(&file.rel_path, zone))
        })
        .collect()
}

// ---------------------------------------------------------------------------
// Detection helpers
// ---------------------------------------------------------------------------

/// Finds the phrase in the text, ensuring it is word-bounded.
/// Returns the byte index of the start of the match.
fn find_word_bounded(text: &str, phrase: &str) -> Option<usize> {
    let mut start = 0;
    while let Some(pos) = text[start..].find(phrase) {
        let abs_pos = start + pos;
        let before_ok = abs_pos == 0 || !text.as_bytes()[abs_pos - 1].is_ascii_alphanumeric();
        let after_pos = abs_pos + phrase.len();
        let after_ok =
            after_pos >= text.len() || !text.as_bytes()[after_pos].is_ascii_alphanumeric();

        if before_ok && after_ok {
            return Some(abs_pos);
        }
        start = abs_pos + 1; // advance to find next
    }
    None
}

/// Checks if the matched phrase is immediately preceded by a negation.
fn is_negated(text: &str, match_pos: usize) -> bool {
    let before = text[..match_pos].trim_end();
    let before_lower = before.to_ascii_lowercase();
    before_lower.ends_with(" not")
        || before_lower.ends_with(" don't")
        || before_lower.ends_with(" dont")
        || before_lower.ends_with(" never")
        || before_lower == "not"
        || before_lower == "don't"
        || before_lower == "dont"
        || before_lower == "never"
}

// ---------------------------------------------------------------------------
// Detection
// ---------------------------------------------------------------------------

fn tier1_hit_for_comment(
    file: &FileInfo,
    line_no: usize,
    comment_text: &str,
) -> Option<LanguageFinding> {
    let lower = comment_text.to_ascii_lowercase();

    // Check nearby allow first
    if nearby_allow(&file.text, line_no, "comment-hygiene") {
        return None;
    }

    for &(phrase, category) in TIER1_ALL.iter() {
        if let Some(pos) = find_word_bounded(&lower, phrase) {
            // Ignore if the phrase is negated (e.g. "do not skip auth")
            if is_negated(&lower, pos) {
                continue;
            }

            let snippet = file
                .text
                .lines()
                .nth(line_no.saturating_sub(1))
                .map(|l| l.trim().chars().take(160).collect::<String>())
                .unwrap_or_default();

            return Some(LanguageFinding::new(
                HLT_RULE_ID,
                "comment-hygiene.hard",
                file.rel_path.clone(),
                Some(line_no),
                snippet.clone(),
                format!(
                    "dangerous comment detected: `{}` phrase found (category: {})",
                    phrase, category
                ),
                format!(
                    "comment confesses {} — this must be resolved before merge",
                    category.replace('-', " ")
                ),
                "resolve the underlying issue described in the comment, then remove the comment; \
                 if the comment documents a necessary tradeoff, use `jankurai:allow comment-hygiene \
                 reason=... expires=...`",
                vec![
                    format!("detector=comment-hygiene.hard"),
                    format!("category={}", category),
                    format!("phrase={}", phrase),
                    format!("path={}", file.rel_path),
                    format!("line={}", line_no),
                    format!("snippet={}", snippet),
                ],
            ));
        }
    }
    None
}

fn tier2_hit_for_comment(
    file: &FileInfo,
    line_no: usize,
    comment_text: &str,
) -> Option<LanguageFinding> {
    let lower = comment_text.to_ascii_lowercase();

    if nearby_allow(&file.text, line_no, "comment-hygiene") {
        return None;
    }

    // Check if any marker word is present (word-bounded)
    let marker = TIER2_MARKERS
        .iter()
        .find(|&&m| find_word_bounded(&lower, m).is_some());

    let marker = match marker {
        Some(m) => *m,
        None => return None,
    };

    // Check if any context noun co-occurs (word-bounded)
    let context = TIER2_CONTEXT_NOUNS
        .iter()
        .find(|&&noun| find_word_bounded(&lower, noun).is_some());

    let context_noun = match context {
        Some(n) => *n,
        None => return None,
    };

    let snippet = file
        .text
        .lines()
        .nth(line_no.saturating_sub(1))
        .map(|l| l.trim().chars().take(160).collect::<String>())
        .unwrap_or_default();

    Some(LanguageFinding::new(
        HLT_RULE_ID,
        "comment-hygiene.advisory",
        file.rel_path.clone(),
        Some(line_no),
        snippet.clone(),
        format!(
            "security-sensitive {} comment: `{}` mentions `{}`",
            marker.to_uppercase(),
            marker,
            context_noun
        ),
        format!(
            "{} marker co-occurs with security/safety term `{}`",
            marker.to_uppercase(),
            context_noun
        ),
        "resolve the security-sensitive TODO or document an explicit exception with \
         `jankurai:allow comment-hygiene reason=... expires=...`",
        vec![
            format!("detector=comment-hygiene.advisory"),
            format!("marker={}", marker),
            format!("context={}", context_noun),
            format!("path={}", file.rel_path),
            format!("line={}", line_no),
            format!("snippet={}", snippet),
        ],
    ))
}

// ---------------------------------------------------------------------------
// Public API (matches rust.rs / typescript.rs pattern)
// ---------------------------------------------------------------------------

const HARD_RULES: &[LanguageRule] = &[LanguageRule {
    id: "comment-hygiene.hard",
    language: Language::Comments,
    hlt_rule_id: HLT_RULE_ID,
    severity: "high",
    category: "vibe",
    lane: "fast",
    confidence: ConfidencePolicy::High,
    matcher: Matcher::NoActiveDetectors, // detection is phrase-based, not simple contains
    proof_window: ProofWindow::None,
    problem: "dangerous comment confesses unresolved security, implementation, or quality issue",
    fix: "resolve the issue described in the comment and remove the comment",
}];

const ADVISORY_RULES: &[LanguageRule] = &[LanguageRule {
    id: "comment-hygiene.advisory",
    language: Language::Comments,
    hlt_rule_id: HLT_RULE_ID,
    severity: "medium",
    category: "vibe",
    lane: "fast",
    confidence: ConfidencePolicy::Medium,
    matcher: Matcher::NoActiveDetectors,
    proof_window: ProofWindow::None,
    problem: "security-sensitive marker comment mentions a safety/security concept",
    fix: "resolve the security-sensitive TODO or document an explicit exception",
}];

pub fn catalog() -> &'static [LanguageRule] {
    static RULES: Lazy<Vec<LanguageRule>> = Lazy::new(|| {
        let mut rules = Vec::new();
        rules.extend_from_slice(HARD_RULES);
        rules.extend_from_slice(ADVISORY_RULES);
        rules
    });
    RULES.as_slice()
}

pub fn findings(ctx: &AuditContext) -> Vec<LanguageFinding> {
    sort_and_cap_findings(hard_findings(ctx), 50)
}

pub fn advisory_signals(ctx: &AuditContext) -> Vec<LanguageFinding> {
    sort_and_cap_findings(advisory_findings(ctx), 50)
}

fn hard_findings(ctx: &AuditContext) -> Vec<LanguageFinding> {
    let mut out = Vec::new();
    for file in scannable_files(ctx) {
        for (idx, line) in file.text.lines().enumerate() {
            let line_no = idx + 1;
            if let Some(comment) = extract_comment(line, &file.suffix) {
                if let Some(hit) = tier1_hit_for_comment(file, line_no, &comment) {
                    out.push(hit);
                }
            }
        }
    }
    out
}

fn advisory_findings(ctx: &AuditContext) -> Vec<LanguageFinding> {
    let mut out = Vec::new();
    for file in scannable_files(ctx) {
        for (idx, line) in file.text.lines().enumerate() {
            let line_no = idx + 1;
            if let Some(comment) = extract_comment(line, &file.suffix) {
                if let Some(hit) = tier2_hit_for_comment(file, line_no, &comment) {
                    out.push(hit);
                }
            }
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn make_file(rel_path: &str, suffix: &str, text: &str) -> FileInfo {
        FileInfo {
            rel_path: rel_path.to_string(),
            name: rel_path.rsplit('/').next().unwrap_or(rel_path).to_string(),
            suffix: suffix.to_string(),
            size: text.len() as u64,
            line_count: text.lines().count(),
            text: text.to_string(),
            is_generated: false,
            is_code: true,
        }
    }

    #[test]
    fn extract_rust_line_comment() {
        assert_eq!(
            extract_comment("  // skip auth check here", ".rs"),
            Some(" skip auth check here".to_string())
        );
    }

    #[test]
    fn extract_rust_doc_comment() {
        assert_eq!(
            extract_comment("  /// documents auth flow", ".rs"),
            Some(" documents auth flow".to_string())
        );
    }

    #[test]
    fn extract_python_hash_comment() {
        assert_eq!(
            extract_comment("  # hardcoded password for dev", ".py"),
            Some(" hardcoded password for dev".to_string())
        );
    }

    #[test]
    fn extract_sql_dash_comment() {
        assert_eq!(
            extract_comment("  -- skip validation", ".sql"),
            Some(" skip validation".to_string())
        );
    }

    #[test]
    fn no_comment_in_code() {
        assert_eq!(extract_comment("  let x = skip_auth();", ".rs"), None);
    }

    #[test]
    fn inline_comment_after_code() {
        let result = extract_comment("  let x = 5; // skip auth check", ".rs");
        assert!(result.is_some());
        assert!(result.unwrap().contains("skip auth check"));
    }

    #[test]
    fn string_literal_not_extracted_as_comment() {
        assert_eq!(
            extract_comment(r#"  let msg = "skip // auth check";"#, ".rs"),
            None
        );
    }

    #[test]
    fn tier1_detects_security_bypass() {
        let file = make_file(
            "src/main.rs",
            ".rs",
            "// skip auth check for now\nfn main() {}",
        );
        let hit = tier1_hit_for_comment(&file, 1, " skip auth check for now");
        assert!(hit.is_some());
        let finding = hit.unwrap();
        assert_eq!(finding.rule_id, HLT_RULE_ID);
        assert!(finding.problem.contains("security-bypass"));
    }

    #[test]
    fn tier1_ignores_normal_comment() {
        let file = make_file(
            "src/main.rs",
            ".rs",
            "// initialize the authentication module\nfn main() {}",
        );
        let hit = tier1_hit_for_comment(&file, 1, " initialize the authentication module");
        assert!(hit.is_none());
    }

    #[test]
    fn tier2_detects_todo_with_auth() {
        let file = make_file(
            "src/main.rs",
            ".rs",
            "// TODO: fix authentication bypass\nfn main() {}",
        );
        let hit = tier2_hit_for_comment(&file, 1, " TODO: fix authentication bypass");
        assert!(hit.is_some());
    }

    #[test]
    fn tier2_ignores_todo_without_security_context() {
        let file = make_file(
            "src/main.rs",
            ".rs",
            "// TODO: refactor this loop\nfn main() {}",
        );
        let hit = tier2_hit_for_comment(&file, 1, " TODO: refactor this loop");
        assert!(hit.is_none());
    }

    #[test]
    fn non_code_extension_not_scannable() {
        let mut file = make_file("docs/auth.md", ".md", "skip auth check");
        file.is_code = false;
        assert!(!is_comment_scannable_file(&file));
    }

    #[test]
    fn test_path_not_scannable() {
        let file = make_file("tests/auth_test.rs", ".rs", "// skip auth check");
        assert!(!is_comment_scannable_file(&file));
    }

    #[test]
    fn jankurai_crate_not_scannable() {
        let file = make_file(
            "crates/jankurai/src/audit/scan.rs",
            ".rs",
            "// skip auth check",
        );
        assert!(!is_comment_scannable_file(&file));
    }
}
