use super::super::catalog::{ConfidencePolicy, Language, LanguageRule, Matcher, ProofWindow};
use super::HLT_RULE_ID;
use once_cell::sync::Lazy;

const HARD_RULES: &[LanguageRule] = &[
    LanguageRule {
        id: "rust.unsafe.undocumented-block",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "high",
        category: "security",
        lane: "fast",
        confidence: ConfidencePolicy::High,
        matcher: Matcher::ContainsAny(&["unsafe {", "unsafe{"]),
        proof_window: ProofWindow::NearbySafetyComment,
        problem: "unsafe block lacks a nearby local safety argument",
        fix: "add a precise `SAFETY:` comment or remove the unsafe block",
    },
    LanguageRule {
        id: "rust.unsafe.public-fn-missing-safety-doc",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "high",
        category: "security",
        lane: "fast",
        confidence: ConfidencePolicy::High,
        matcher: Matcher::ContainsAny(&[
            "pub unsafe fn",
            "pub(crate) unsafe fn",
            "pub(super) unsafe fn",
        ]),
        proof_window: ProofWindow::NearbySafetyDocs,
        problem: "public unsafe API lacks a `# Safety` contract",
        fix: "document caller obligations with a `# Safety` section",
    },
    LanguageRule {
        id: "rust.unsafe.impl-send-sync",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "high",
        category: "security",
        lane: "fast",
        confidence: ConfidencePolicy::High,
        matcher: Matcher::ContainsAny(&["unsafe impl send", "unsafe impl sync"]),
        proof_window: ProofWindow::NearbySafetyDocs,
        problem: "unsafe Send/Sync impl needs a thread-safety proof",
        fix: "remove the unsafe impl or document and prove the synchronization invariant",
    },
    LanguageRule {
        id: "rust.unsafe.transmute",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "high",
        category: "security",
        lane: "fast",
        confidence: ConfidencePolicy::High,
        matcher: Matcher::ContainsAny(&["transmute("]),
        proof_window: ProofWindow::NearbySafetyComment,
        problem: "transmute hides layout, validity, or lifetime assumptions",
        fix: "replace transmute with an explicit conversion that proves layout and validity",
    },
    LanguageRule {
        id: "rust.unsafe.assume-init",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "high",
        category: "security",
        lane: "fast",
        confidence: ConfidencePolicy::High,
        matcher: Matcher::ContainsAny(&["assume_init("]),
        proof_window: ProofWindow::NearbySafetyComment,
        problem: "assume_init can read uninitialized memory",
        fix: "initialize every field before converting from MaybeUninit",
    },
    LanguageRule {
        id: "rust.unsafe.zeroed",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "high",
        category: "security",
        lane: "fast",
        confidence: ConfidencePolicy::High,
        matcher: Matcher::ContainsAny(&["zeroed("]),
        proof_window: ProofWindow::NearbySafetyComment,
        problem: "mem::zeroed can fabricate invalid values",
        fix: "construct the type with a valid initializer instead of zeroing it",
    },
    LanguageRule {
        id: "rust.unsafe.get-unchecked",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "high",
        category: "security",
        lane: "fast",
        confidence: ConfidencePolicy::High,
        matcher: Matcher::ContainsAny(&["get_unchecked("]),
        proof_window: ProofWindow::NearbySafetyComment,
        problem: "unchecked indexing needs a mechanical bounds proof",
        fix: "replace unchecked access with a checked access path or prove the bounds locally",
    },
    LanguageRule {
        id: "rust.unsafe.unwrap-unchecked",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "high",
        category: "security",
        lane: "fast",
        confidence: ConfidencePolicy::High,
        matcher: Matcher::ContainsAny(&["unwrap_unchecked("]),
        proof_window: ProofWindow::NearbySafetyComment,
        problem: "unwrap_unchecked bypasses the option/result proof",
        fix: "use a checked path or add a local proof that the value is always present",
    },
    LanguageRule {
        id: "rust.unsafe.unreachable-unchecked",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "high",
        category: "security",
        lane: "fast",
        confidence: ConfidencePolicy::High,
        matcher: Matcher::ContainsAny(&["unreachable_unchecked("]),
        proof_window: ProofWindow::NearbySafetyComment,
        problem: "unreachable_unchecked assumes a proof that reviewers cannot infer",
        fix: "replace it with a checked branch or a documented invariant",
    },
    LanguageRule {
        id: "rust.unsafe.from-utf8-unchecked",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "high",
        category: "security",
        lane: "fast",
        confidence: ConfidencePolicy::High,
        matcher: Matcher::ContainsAny(&["from_utf8_unchecked("]),
        proof_window: ProofWindow::NearbySafetyComment,
        problem: "unchecked UTF-8 conversion can fabricate invalid text",
        fix: "validate the bytes or keep the value as raw bytes",
    },
    LanguageRule {
        id: "rust.unsafe.raw-parts",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "high",
        category: "security",
        lane: "fast",
        confidence: ConfidencePolicy::High,
        matcher: Matcher::ContainsAny(&[
            "from_raw_parts(",
            "Box::from_raw(",
            "Vec::from_raw_parts(",
            "CString::from_raw(",
        ]),
        proof_window: ProofWindow::NearbySafetyComment,
        problem: "raw ownership conversion needs exact provenance and allocator proof",
        fix: "use the matching constructor/destructor pair or add a documented ownership proof",
    },
    LanguageRule {
        id: "rust.unsafe.static-mut",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "high",
        category: "security",
        lane: "fast",
        confidence: ConfidencePolicy::High,
        matcher: Matcher::ContainsAny(&["static mut"]),
        proof_window: ProofWindow::NearbySafetyComment,
        problem: "static mut exposes unsynchronized global mutation",
        fix: "replace the mutable static with explicit synchronization or scoped ownership",
    },
    LanguageRule {
        id: "rust.unsafe.repr-packed",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "high",
        category: "security",
        lane: "fast",
        confidence: ConfidencePolicy::High,
        matcher: Matcher::ContainsAny(&["repr(packed)"]),
        proof_window: ProofWindow::NearbySafetyComment,
        problem: "repr(packed) makes alignment-sensitive references dangerous",
        fix: "remove packed layout or access fields through unaligned-safe primitives",
    },
    LanguageRule {
        id: "rust.supply.allow-warnings",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "high",
        category: "security",
        lane: "fast",
        confidence: ConfidencePolicy::Medium,
        matcher: Matcher::ContainsAny(&[
            "allow(warnings)",
            "allow(clippy::all)",
            "allow(clippy::correctness)",
        ]),
        proof_window: ProofWindow::NearbySafetyDocs,
        problem: "broad lint suppression hides review-relevant issues",
        fix: "tighten the lint scope or remove the allow entirely",
    },
    LanguageRule {
        id: "rust.supply.rustflags-warn-suppression",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "high",
        category: "security",
        lane: "fast",
        confidence: ConfidencePolicy::Medium,
        matcher: Matcher::ContainsAny(&["-a warnings", "-awarnings"]),
        proof_window: ProofWindow::NearbySafetyDocs,
        problem: "RUSTFLAGS warning suppression hides build diagnostics",
        fix: "remove warning suppression and fix the underlying warnings",
    },
    LanguageRule {
        id: "rust.security.shell-c-dynamic",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "high",
        category: "security",
        lane: "fast",
        confidence: ConfidencePolicy::High,
        matcher: Matcher::ContainsAll(&["command::new(", ".arg(\"-c\")"]),
        proof_window: ProofWindow::NearbyAsyncContext,
        problem: "shell execution with dynamic command text is unsafe by default",
        fix: "pass argv values directly or use a bounded, allowlisted command path",
    },
    LanguageRule {
        id: "rust.async.unbounded-channel",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "high",
        category: "security",
        lane: "fast",
        confidence: ConfidencePolicy::High,
        matcher: Matcher::ContainsAny(&["unbounded_channel(", "unbounded("]),
        proof_window: ProofWindow::NearbyAsyncContext,
        problem: "unbounded channel or task creation needs explicit backpressure proof",
        fix: "use a bounded channel or document the queue bound and shutdown path",
    },
    LanguageRule {
        id: "rust.async.block_on-in-async",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "high",
        category: "security",
        lane: "fast",
        confidence: ConfidencePolicy::High,
        matcher: Matcher::ContainsAny(&["block_on("]),
        proof_window: ProofWindow::NearbyAsyncContext,
        problem: "blocking inside async context can stall the executor",
        fix: "move the work out of async context or use an async-native path",
    },
];

const ADVISORY_RULES: &[LanguageRule] = &[
    LanguageRule {
        id: "rust.review.clone-overuse",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "medium",
        category: "review",
        lane: "fast",
        confidence: ConfidencePolicy::Low,
        matcher: Matcher::ContainsAny(&[".clone(", "clone()"]),
        proof_window: ProofWindow::None,
        problem: "clone may be hiding ownership or performance drift",
        fix: "prefer borrowing or move semantics when the copy is not essential",
    },
    LanguageRule {
        id: "rust.review.arc-mutex-default",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "medium",
        category: "review",
        lane: "fast",
        confidence: ConfidencePolicy::Low,
        matcher: Matcher::ContainsAny(&["Arc<Mutex<", "Arc<tokio::sync::Mutex<"]),
        proof_window: ProofWindow::None,
        problem: "Arc<Mutex<_>> may be a default ownership escape hatch",
        fix: "consider explicit ownership or a bounded message-passing boundary",
    },
    LanguageRule {
        id: "rust.review.rc-refcell-default",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "medium",
        category: "review",
        lane: "fast",
        confidence: ConfidencePolicy::Low,
        matcher: Matcher::ContainsAny(&["Rc<RefCell<"]),
        proof_window: ProofWindow::None,
        problem: "Rc<RefCell<_>> may be hiding interior mutability",
        fix: "encode the ownership model more directly or document the single-threaded invariant",
    },
    LanguageRule {
        id: "rust.review.as-cast",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "medium",
        category: "review",
        lane: "fast",
        confidence: ConfidencePolicy::Low,
        matcher: Matcher::ContainsAny(&[" as "]),
        proof_window: ProofWindow::None,
        problem: "broad as-casts can hide truncation or type dishonesty",
        fix: "use TryFrom, helper newtypes, or a proof-oriented conversion",
    },
    LanguageRule {
        id: "rust.review.repr-c",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "medium",
        category: "review",
        lane: "fast",
        confidence: ConfidencePolicy::Low,
        matcher: Matcher::ContainsAny(&["repr(C)", "repr(C,"]),
        proof_window: ProofWindow::None,
        problem: "repr(C) is a contract surface that needs review",
        fix: "document the ABI and ownership story next to the type definition",
    },
    LanguageRule {
        id: "rust.review.pin",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "medium",
        category: "review",
        lane: "fast",
        confidence: ConfidencePolicy::Low,
        matcher: Matcher::ContainsAny(&["Pin<", "Pin::new_unchecked", "pin_project"]),
        proof_window: ProofWindow::None,
        problem: "Pin usage deserves a locality proof even when it is valid",
        fix: "document the pinning contract and keep the projection code small",
    },
    LanguageRule {
        id: "rust.review.atomics",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "medium",
        category: "review",
        lane: "fast",
        confidence: ConfidencePolicy::Low,
        matcher: Matcher::ContainsAny(&["Atomic", "Ordering::Relaxed"]),
        proof_window: ProofWindow::None,
        problem: "atomics need an explicit ordering story",
        fix: "document the memory-order invariant next to the atomic",
    },
    LanguageRule {
        id: "rust.review.generic-unwrap",
        language: Language::Rust,
        hlt_rule_id: HLT_RULE_ID,
        severity: "medium",
        category: "review",
        lane: "fast",
        confidence: ConfidencePolicy::Low,
        matcher: Matcher::ContainsAny(&["unwrap(", "expect("]),
        proof_window: ProofWindow::None,
        problem: "generic unwrap/expect in non-test Rust code deserves a proof check",
        fix: "replace the panic path with a typed error or a documented invariant",
    },
];

pub fn catalog() -> &'static [LanguageRule] {
    static RULES: Lazy<Vec<LanguageRule>> = Lazy::new(|| {
        let mut rules = Vec::new();
        rules.extend_from_slice(HARD_RULES);
        rules.extend_from_slice(ADVISORY_RULES);
        rules
    });
    RULES.as_slice()
}
