#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RepairEligibility {
    AutoSafe,
    AgentAssisted,
    HumanRequired,
    NeverAuto,
}

impl RepairEligibility {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::AutoSafe => "auto-safe",
            Self::AgentAssisted => "agent-assisted",
            Self::HumanRequired => "agent-assisted",
            Self::NeverAuto => "never-auto",
        }
    }

    pub fn allows_auto_pr(self) -> bool {
        matches!(self, Self::AutoSafe | Self::AgentAssisted)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RepairRisk {
    Low,
    Medium,
    High,
    Critical,
}

impl RepairRisk {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Low => "low",
            Self::Medium => "medium",
            Self::High => "high",
            Self::Critical => "critical",
        }
    }

    pub fn rank(self) -> u8 {
        match self {
            Self::Low => 1,
            Self::Medium => 2,
            Self::High => 3,
            Self::Critical => 4,
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "low" => Some(Self::Low),
            "medium" => Some(Self::Medium),
            "high" => Some(Self::High),
            "critical" => Some(Self::Critical),
            _ => None,
        }
    }

    pub fn is_allowed_by(self, max: Self) -> bool {
        self.rank() <= max.rank()
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RuleStatus {
    Stable,
    Experimental,
    Deprecated,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConfidencePolicy {
    High,
    Medium,
    Low,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RuleSpec {
    pub id: &'static str,
    pub name: &'static str,
    pub category: &'static str,
    pub tlr: &'static str,
    pub lane: &'static str,
    pub docs_url: &'static str,
    pub owner_hint: &'static str,
    pub evidence_kind: &'static str,
    pub severity: &'static str,
    pub repairable: bool,
    pub repair_eligibility: RepairEligibility,
    pub repair_risk: RepairRisk,
    pub repair_reason: &'static str,
    pub status: RuleStatus,
    pub standard_section: &'static str,
    pub cap_key: Option<&'static str>,
    pub confidence_policy: ConfidencePolicy,
}

pub const RULES: &[RuleSpec] = &[
    RuleSpec {
        id: "HLT-001-DEAD-MARKER",
        name: "Future-hostile language and placeholder markers",
        category: "vibe",
        tlr: "Entropy",
        lane: "fast",
        docs_url: "docs/audit-rubric.md#future-hostile-language-rule",
        owner_hint: "tools",
        evidence_kind: "repository-scan",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::AgentAssisted,
        repair_risk: RepairRisk::Medium,
        repair_reason: "marker cleanup is scoped but still needs proof that intent was not removed",
        status: RuleStatus::Stable,
        standard_section: "Entropy",
        cap_key: Some("future-hostile-dead-language-in-product-code"),
        confidence_policy: ConfidencePolicy::Medium,
    },
    RuleSpec {
        id: "HLT-002-GENERATED-MUTATION",
        name: "Generated zone mutation risk",
        category: "generated",
        tlr: "Contracts/data",
        lane: "contract",
        docs_url: "agent/JANKURAI_STANDARD.md#generated-zones",
        owner_hint: "tools",
        evidence_kind: "contract-manifest",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason: "generated artifacts require source or generator review before repair",
        status: RuleStatus::Stable,
        standard_section: "Generated Zones",
        cap_key: Some("generated-zone-mutation-risk"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-003-OWNERLESS-PATH",
        name: "Ownerless path",
        category: "context",
        tlr: "Context/setup",
        lane: "fast",
        docs_url: "agent/JANKURAI_STANDARD.md#ownership-boundaries",
        owner_hint: "agent",
        evidence_kind: "policy-manifest",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::AgentAssisted,
        repair_risk: RepairRisk::Medium,
        repair_reason: "ownership map edits are bounded but affect agent routing",
        status: RuleStatus::Stable,
        standard_section: "Ownership Boundaries",
        cap_key: None,
        confidence_policy: ConfidencePolicy::Medium,
    },
    RuleSpec {
        id: "HLT-004-UNMAPPED-PROOF",
        name: "Unmapped proof lane",
        category: "proof",
        tlr: "Verification",
        lane: "fast",
        docs_url: "agent/JANKURAI_STANDARD.md#proof-lanes",
        owner_hint: "tools",
        evidence_kind: "policy-manifest",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::AgentAssisted,
        repair_risk: RepairRisk::Medium,
        repair_reason: "proof routing repairs are bounded but must preserve validation coverage",
        status: RuleStatus::Stable,
        standard_section: "Proof Lanes",
        cap_key: None,
        confidence_policy: ConfidencePolicy::Medium,
    },
    RuleSpec {
        id: "HLT-005-PYTHON-PRODUCT-TRUTH",
        name: "Python product truth spill",
        category: "python",
        tlr: "Business truth",
        lane: "contract",
        docs_url: "docs/agent-native-standard.md",
        owner_hint: "tools",
        evidence_kind: "repository-scan",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason: "product truth boundary changes require architectural review",
        status: RuleStatus::Stable,
        standard_section: "Python Boundary",
        cap_key: Some("python-direct-product-truth-or-db-ownership"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-006-DIRECT-DB-WRONG-LAYER",
        name: "Direct DB access from wrong layer",
        category: "data",
        tlr: "Contracts/data",
        lane: "db",
        docs_url: "docs/audit-rubric.md#required-shape",
        owner_hint: "tools",
        evidence_kind: "sql",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason: "database layer movement can affect durable data behavior",
        status: RuleStatus::Stable,
        standard_section: "Database Boundary",
        cap_key: Some("direct-db-access-from-wrong-layer"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-007-HANDWRITTEN-CONTRACT",
        name: "Handwritten contract drift",
        category: "boundary",
        tlr: "Contracts/data",
        lane: "contract",
        docs_url: "docs/audit-rubric.md#known-vibe-coding-insults",
        owner_hint: "tools",
        evidence_kind: "contract-manifest",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason: "contract drift repair can alter public API compatibility",
        status: RuleStatus::Stable,
        standard_section: "Contract Boundaries",
        cap_key: Some("generated-contracts-or-public-api-drift-untested"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-008-FALSE-GREEN-RISK",
        name: "False green test risk",
        category: "test",
        tlr: "Verification",
        lane: "fast",
        docs_url: "docs/testing.md",
        owner_hint: "tools",
        evidence_kind: "test",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::AgentAssisted,
        repair_risk: RepairRisk::Medium,
        repair_reason: "test proof repairs are scoped but can create false confidence",
        status: RuleStatus::Stable,
        standard_section: "Testing",
        cap_key: Some("false-green-test-risk"),
        confidence_policy: ConfidencePolicy::Medium,
    },
    RuleSpec {
        id: "HLT-009-GENERATED-SECURITY",
        name: "Generated security gap",
        category: "security",
        tlr: "Security, secrets, agency",
        lane: "security",
        docs_url: "docs/audit-rubric.md#top-level-risk-mapping",
        owner_hint: "ops",
        evidence_kind: "workflow-command",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason: "generated security behavior must be reviewed before repair",
        status: RuleStatus::Stable,
        standard_section: "Security Lanes",
        cap_key: Some("no-security-lane-on-high-risk-repo"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-010-SECRET-SPRAWL",
        name: "Secret-like content detected",
        category: "security",
        tlr: "Security, secrets, agency",
        lane: "security",
        docs_url: "docs/audit-rubric.md#top-level-risk-mapping",
        owner_hint: "ops",
        evidence_kind: "repository-scan",
        severity: "critical",
        repairable: true,
        repair_eligibility: RepairEligibility::NeverAuto,
        repair_risk: RepairRisk::Critical,
        repair_reason: "secret exposure requires human-led rotation and incident review",
        status: RuleStatus::Stable,
        standard_section: "Secrets",
        cap_key: Some("secret-like-content-detected"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-011-PROMPT-INJECTION",
        name: "Prompt injection risk",
        category: "security",
        tlr: "Security, secrets, agency",
        lane: "security",
        docs_url: "docs/audit-rubric.md#top-level-risk-mapping",
        owner_hint: "ops",
        evidence_kind: "policy-manifest",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason: "trusted policy changes require human review against prompt injection",
        status: RuleStatus::Stable,
        standard_section: "Prompt Injection",
        cap_key: Some("prompt-injection-risk"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-012-OVERBROAD-AGENCY",
        name: "Overbroad agent agency",
        category: "security",
        tlr: "Security, secrets, agency",
        lane: "security",
        docs_url: "docs/audit-rubric.md#top-level-risk-mapping",
        owner_hint: "ops",
        evidence_kind: "policy-manifest",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason: "agent authority changes require explicit human approval",
        status: RuleStatus::Stable,
        standard_section: "Agent Authority",
        cap_key: Some("overbroad-agent-agency"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-013-RENDERED-UX-GAP",
        name: "Rendered UX proof gap",
        category: "ux-qa",
        tlr: "Verification and rendered UX",
        lane: "web",
        docs_url: "docs/testing.md",
        owner_hint: "tools",
        evidence_kind: "ux-proof",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason: "user-facing UX proof gaps require rendered evidence review",
        status: RuleStatus::Stable,
        standard_section: "UX QA",
        cap_key: Some("missing-rendered-ux-qa-lane"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-014-A11Y-GAP",
        name: "Accessibility proof gap",
        category: "ux-qa",
        tlr: "Verification and rendered UX",
        lane: "web",
        docs_url: "docs/agent-native-standard.md",
        owner_hint: "tools",
        evidence_kind: "ux-proof",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason: "accessibility fixes require rendered and assistive proof review",
        status: RuleStatus::Stable,
        standard_section: "Accessibility",
        cap_key: None,
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-015-CONTEXT-SETUP-GAP",
        name: "Context and setup gap",
        category: "context",
        tlr: "Context/setup",
        lane: "fast",
        docs_url: "docs/agent-native-standard.md",
        owner_hint: "agent",
        evidence_kind: "policy-manifest",
        severity: "medium",
        repairable: true,
        repair_eligibility: RepairEligibility::AgentAssisted,
        repair_risk: RepairRisk::Medium,
        repair_reason: "context setup repairs are bounded but affect agent bootstrap behavior",
        status: RuleStatus::Stable,
        standard_section: "Agent Context",
        cap_key: Some("no-root-agent-instructions"),
        confidence_policy: ConfidencePolicy::Medium,
    },
    RuleSpec {
        id: "HLT-016-SUPPLY-CHAIN-DRIFT",
        name: "Supply-chain drift",
        category: "security",
        tlr: "Security, secrets, agency",
        lane: "security",
        docs_url: "docs/audit-rubric.md#top-level-risk-mapping",
        owner_hint: "ops",
        evidence_kind: "workflow-command",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason: "supply-chain changes require provenance and dependency review",
        status: RuleStatus::Stable,
        standard_section: "Supply Chain",
        cap_key: Some("no-secret-or-dependency-scanning-in-ci"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-017-OPAQUE-OBSERVABILITY",
        name: "Opaque observability",
        category: "observability",
        tlr: "Repair",
        lane: "observability",
        docs_url: "agent/JANKURAI_STANDARD.md#repair-receipts",
        owner_hint: "tools",
        evidence_kind: "repository-scan",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::AgentAssisted,
        repair_risk: RepairRisk::Medium,
        repair_reason: "observability repairs are typically scoped to telemetry and error receipts",
        status: RuleStatus::Stable,
        standard_section: "Observability",
        cap_key: None,
        confidence_policy: ConfidencePolicy::Medium,
    },
    RuleSpec {
        id: "HLT-018-PERF-CONCURRENCY-DRIFT",
        name: "Performance and concurrency drift",
        category: "proof",
        tlr: "Verification",
        lane: "fast",
        docs_url: "docs/testing.md",
        owner_hint: "tools",
        evidence_kind: "repository-scan",
        severity: "medium",
        repairable: true,
        repair_eligibility: RepairEligibility::AgentAssisted,
        repair_risk: RepairRisk::Medium,
        repair_reason:
            "performance and concurrency repairs require targeted proof but can be planned narrowly",
        status: RuleStatus::Stable,
        standard_section: "Performance",
        cap_key: None,
        confidence_policy: ConfidencePolicy::Medium,
    },
    RuleSpec {
        id: "HLT-019-STREAMING-RUNTIME-DRIFT",
        name: "Streaming runtime drift",
        category: "boundary",
        tlr: "Contracts/data",
        lane: "db",
        docs_url: "docs/streaming.md",
        owner_hint: "tools",
        evidence_kind: "boundary-scan",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason: "streaming runtime boundaries can affect production integration behavior",
        status: RuleStatus::Stable,
        standard_section: "Streaming",
        cap_key: Some("streaming-runtime-drift"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-020-CI-HARDENING-GAP",
        name: "CI workflow hardening gap",
        category: "security",
        tlr: "Security, secrets, agency",
        lane: "security",
        docs_url: "docs/audit-rubric.md#top-level-risk-mapping",
        owner_hint: "ops",
        evidence_kind: "policy-manifest",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason: "CI hardening changes alter release authority and require review",
        status: RuleStatus::Stable,
        standard_section: "CI Hardening",
        cap_key: Some("no-jankurai-audit-lane-in-ci"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-021-DESTRUCTIVE-MIGRATION",
        name: "Destructive SQL migration without safety evidence",
        category: "data",
        tlr: "Contracts/data",
        lane: "db-migration-analyze",
        docs_url: "docs/BAD_MIGRATION.md",
        owner_hint: "tools",
        evidence_kind: "sql",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason:
            "destructive migrations require documented rollback, backfill, and lock safety",
        status: RuleStatus::Stable,
        standard_section: "Migrations",
        cap_key: Some("destructive-migration-risk"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-022-AUTHZ-ISOLATION-GAP",
        name: "Authorization and data-isolation proof gap",
        category: "security",
        tlr: "Business truth",
        lane: "db",
        docs_url: "docs/audit-rubric.md#top-level-risk-mapping",
        owner_hint: "tools",
        evidence_kind: "boundary-scan",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason: "authorization and tenant isolation gaps require reviewed negative tests",
        status: RuleStatus::Stable,
        standard_section: "Authorization",
        cap_key: Some("authz-or-data-isolation-gap"),
        confidence_policy: ConfidencePolicy::Medium,
    },
    RuleSpec {
        id: "HLT-023-INPUT-BOUNDARY-GAP",
        name: "Input boundary proof gap",
        category: "security",
        tlr: "Security, secrets, agency",
        lane: "security",
        docs_url: "docs/audit-rubric.md#top-level-risk-mapping",
        owner_hint: "ops",
        evidence_kind: "repository-scan",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason: "unsafe sinks and unvalidated boundaries can become exploitable behavior",
        status: RuleStatus::Stable,
        standard_section: "Input Boundaries",
        cap_key: Some("input-boundary-gap"),
        confidence_policy: ConfidencePolicy::Medium,
    },
    RuleSpec {
        id: "HLT-024-AGENT-TOOL-SUPPLY-GAP",
        name: "Agent tool supply-chain proof gap",
        category: "security",
        tlr: "Security, secrets, agency",
        lane: "security",
        docs_url: "docs/audit-rubric.md#top-level-risk-mapping",
        owner_hint: "ops",
        evidence_kind: "policy-manifest",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason: "agent tool and MCP trust changes alter execution authority",
        status: RuleStatus::Stable,
        standard_section: "Agent Tool Supply",
        cap_key: Some("agent-tool-supply-chain-gap"),
        confidence_policy: ConfidencePolicy::Medium,
    },
    RuleSpec {
        id: "HLT-025-RELEASE-READINESS-GAP",
        name: "Release readiness proof gap",
        category: "release",
        tlr: "Verification",
        lane: "release",
        docs_url: "docs/testing.md",
        owner_hint: "tools",
        evidence_kind: "workflow-command",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason: "launch gates must prove backups, monitoring, security, and rollback",
        status: RuleStatus::Stable,
        standard_section: "Release Readiness",
        cap_key: Some("release-readiness-gap"),
        confidence_policy: ConfidencePolicy::Medium,
    },
    RuleSpec {
        id: "HLT-026-COST-BUDGET-GAP",
        name: "Cost and budget proof gap",
        category: "release",
        tlr: "Verification",
        lane: "release",
        docs_url: "docs/testing.md",
        owner_hint: "tools",
        evidence_kind: "policy-manifest",
        severity: "medium",
        repairable: true,
        repair_eligibility: RepairEligibility::AgentAssisted,
        repair_risk: RepairRisk::Medium,
        repair_reason: "cost controls are bounded but need explicit budgets and stop conditions",
        status: RuleStatus::Stable,
        standard_section: "Cost Budgets",
        cap_key: None,
        confidence_policy: ConfidencePolicy::Medium,
    },
    RuleSpec {
        id: "HLT-027-HUMAN-REVIEW-EVIDENCE-GAP",
        name: "Human review evidence gap",
        category: "proof",
        tlr: "Repair",
        lane: "audit",
        docs_url: "docs/testing.md",
        owner_hint: "tools",
        evidence_kind: "receipt",
        severity: "medium",
        repairable: true,
        repair_eligibility: RepairEligibility::AgentAssisted,
        repair_risk: RepairRisk::Medium,
        repair_reason: "human review and proof claims must be backed by reproducible evidence",
        status: RuleStatus::Stable,
        standard_section: "Human Review Evidence",
        cap_key: None,
        confidence_policy: ConfidencePolicy::Medium,
    },
    RuleSpec {
        id: "HLT-028-BOUNDARY-EVIDENCE-GAP",
        name: "Audited runtime boundary evidence gap",
        category: "boundary",
        tlr: "Contracts/data",
        lane: "contract",
        docs_url: "docs/agent-native-standard.md",
        owner_hint: "tools",
        evidence_kind: "boundary-evidence",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason:
            "runtime boundary reclassification can alter target-stack cap pressure and needs deterministic evidence",
        status: RuleStatus::Stable,
        standard_section: "Runtime Boundary Evidence",
        cap_key: Some("boundary-reclassification-evidence-gap"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-029-RUST-BAD-BEHAVIOR",
        name: "Rust bad behavior",
        category: "security",
        tlr: "Security, secrets, agency",
        lane: "fast",
        docs_url: "docs/audit-rubric.md#top-level-risk-mapping",
        owner_hint: "tools",
        evidence_kind: "repository-scan",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason: "Rust bad-behavior findings require a local proof or design change before repair",
        status: RuleStatus::Stable,
        standard_section: "Language Bad Behavior",
        cap_key: Some("rust-bad-behavior"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-030-SQL-BAD-BEHAVIOR",
        name: "SQL bad behavior",
        category: "data",
        tlr: "Contracts/data",
        lane: "db",
        docs_url: "docs/BAD_SQL.md",
        owner_hint: "tools",
        evidence_kind: "sql",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason: "SQL bad-behavior findings require query or migration proof before repair",
        status: RuleStatus::Stable,
        standard_section: "Language Bad Behavior",
        cap_key: Some("sql-bad-behavior"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-031-TYPESCRIPT-BAD-BEHAVIOR",
        name: "TypeScript bad behavior",
        category: "boundary",
        tlr: "Contracts/data",
        lane: "fast",
        docs_url: "docs/testing.md",
        owner_hint: "tools",
        evidence_kind: "repository-scan",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason: "TypeScript bad-behavior findings require boundary proof before repair",
        status: RuleStatus::Stable,
        standard_section: "Language Bad Behavior",
        cap_key: Some("typescript-bad-behavior"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-032-DOCKER-BAD-BEHAVIOR",
        name: "Docker bad behavior",
        category: "security",
        tlr: "Security, secrets, agency",
        lane: "security",
        docs_url: "docs/testing.md",
        owner_hint: "ops",
        evidence_kind: "workflow-command",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason: "Docker bad-behavior findings require a reviewed container or build proof",
        status: RuleStatus::Stable,
        standard_section: "Language Bad Behavior",
        cap_key: Some("docker-bad-behavior"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-033-PYTHON-BAD-BEHAVIOR",
        name: "Python bad behavior",
        category: "python",
        tlr: "Business truth",
        lane: "contract",
        docs_url: "docs/testing.md",
        owner_hint: "tools",
        evidence_kind: "repository-scan",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason: "Python bad-behavior findings require boundary proof before repair",
        status: RuleStatus::Stable,
        standard_section: "Language Bad Behavior",
        cap_key: Some("python-bad-behavior"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-034-CI-BAD-BEHAVIOR",
        name: "CI bad behavior",
        category: "security",
        tlr: "Security, secrets, agency",
        lane: "security",
        docs_url: "docs/testing.md",
        owner_hint: "ops",
        evidence_kind: "workflow-command",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason: "CI bad-behavior findings require reviewed workflow evidence before repair",
        status: RuleStatus::Stable,
        standard_section: "Language Bad Behavior",
        cap_key: Some("ci-bad-behavior"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-035-GIT-BAD-BEHAVIOR",
        name: "Git bad behavior",
        category: "agent",
        tlr: "Context/setup",
        lane: "audit",
        docs_url: "docs/testing.md",
        owner_hint: "agent",
        evidence_kind: "repository-scan",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason: "Git bad-behavior findings require reviewed automation or hook evidence before repair",
        status: RuleStatus::Stable,
        standard_section: "Language Bad Behavior",
        cap_key: Some("git-bad-behavior"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-036-GITTOOLS-BAD-BEHAVIOR",
        name: "GitTools bad behavior",
        category: "agent",
        tlr: "Context/setup",
        lane: "audit",
        docs_url: "docs/BAD_gittools.md",
        owner_hint: "agent",
        evidence_kind: "repository-scan",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason: "Git tooling bad-behavior findings require reviewed hook, CI, or policy-tool evidence before repair",
        status: RuleStatus::Stable,
        standard_section: "Language Bad Behavior",
        cap_key: Some("gittools-bad-behavior"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-037-RELEASE-BAD-BEHAVIOR",
        name: "Release bad behavior",
        category: "release",
        tlr: "Verification",
        lane: "release",
        docs_url: "docs/BAD_release.md",
        owner_hint: "ops",
        evidence_kind: "release-policy",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason: "Release bad-behavior findings require reviewed version, tag, artifact, provenance, and rollback evidence before repair",
        status: RuleStatus::Stable,
        standard_section: "Language Bad Behavior",
        cap_key: Some("release-bad-behavior"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-038-REFERENCE-PROFILE-STRUCTURE-GAP",
        name: "Reference profile structure gap",
        category: "context",
        tlr: "Context/setup",
        lane: "fast",
        docs_url: "docs/audit-rubric.md#required-shape",
        owner_hint: "agent",
        evidence_kind: "repository-scan",
        severity: "medium",
        repairable: true,
        repair_eligibility: RepairEligibility::AgentAssisted,
        repair_risk: RepairRisk::Medium,
        repair_reason:
            "reference-profile structure repairs are scoped routing changes with migration steering",
        status: RuleStatus::Stable,
        standard_section: "Ownership and navigation surface",
        cap_key: None,
        confidence_policy: ConfidencePolicy::Medium,
    },
    RuleSpec {
        id: "HLT-039-WEB-SECURITY-BAD-BEHAVIOR",
        name: "Web security bad behavior",
        category: "security",
        tlr: "Security, secrets, agency",
        lane: "security",
        docs_url: "docs/language-bad-behavior.md#web-security-and-repo-rot-detectors",
        owner_hint: "ops",
        evidence_kind: "repository-scan",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason:
            "web security findings can alter auth, session, CORS, or deployment behavior and require reviewed security proof",
        status: RuleStatus::Stable,
        standard_section: "Language Bad Behavior",
        cap_key: Some("web-security-bad-behavior"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-040-REPO-ROT-BAD-BEHAVIOR",
        name: "Repository rot bad behavior",
        category: "context",
        tlr: "Context/setup",
        lane: "audit",
        docs_url: "docs/language-bad-behavior.md#web-security-and-repo-rot-detectors",
        owner_hint: "agent",
        evidence_kind: "repository-scan",
        severity: "medium",
        repairable: true,
        repair_eligibility: RepairEligibility::AgentAssisted,
        repair_risk: RepairRisk::Medium,
        repair_reason:
            "repo-rot cleanup is usually scoped but must not delete live compatibility, migration, or generated evidence",
        status: RuleStatus::Stable,
        standard_section: "Ownership and navigation surface",
        cap_key: Some("repo-rot-bad-behavior"),
        confidence_policy: ConfidencePolicy::Medium,
    },
    RuleSpec {
        id: "HLT-041-COMMENT-HYGIENE",
        name: "Dangerous comment hygiene",
        category: "vibe",
        tlr: "Entropy",
        lane: "fast",
        docs_url: "docs/BAD_COMMENTS.md",
        owner_hint: "tools",
        evidence_kind: "repository-scan",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::AgentAssisted,
        repair_risk: RepairRisk::Medium,
        repair_reason:
            "comment cleanup is scoped but must not remove intentional safety documentation",
        status: RuleStatus::Stable,
        standard_section: "Comment Hygiene",
        cap_key: Some("comment-hygiene-dangerous-residue"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-042-CI-LOCAL-PARITY",
        name: "CI lacks local-run parity",
        category: "ci",
        tlr: "Verification",
        lane: "fast",
        docs_url: "docs/ci-local.md",
        owner_hint: "ops",
        evidence_kind: "repository-scan",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::AgentAssisted,
        repair_risk: RepairRisk::Low,
        repair_reason:
            "extracting workflow steps into ops/ci/*.sh and adding local runners is mechanical",
        status: RuleStatus::Stable,
        standard_section: "CI Local Parity",
        cap_key: Some("ci-local-parity"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-043-COPY-PASTE-BAD-BEHAVIOR",
        name: "Copy-code redundancy in active source",
        category: "copy-code",
        tlr: "Maintainability entropy",
        lane: "copy-code",
        docs_url: "docs/BAD_COPY.md",
        owner_hint: "tools",
        evidence_kind: "repository-scan",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason:
            "high-confidence copy-code classes should be consolidated under one owner before repair",
        status: RuleStatus::Stable,
        standard_section: "Copy-Code Redundancy",
        cap_key: Some("severe-duplication-in-product-code"),
        confidence_policy: ConfidencePolicy::High,
    },
    RuleSpec {
        id: "HLT-044-WORKTREE-SPRAWL",
        name: "Worktree sprawl across same-origin sibling checkouts",
        category: "governance",
        tlr: "Context/setup",
        lane: "audit",
        docs_url: "agent/JANKURAI_STANDARD.md#ownership-boundaries",
        owner_hint: "agent",
        evidence_kind: "repository-scan",
        severity: "high",
        repairable: true,
        repair_eligibility: RepairEligibility::HumanRequired,
        repair_risk: RepairRisk::High,
        repair_reason:
            "consolidating parallel same-origin checkouts moves working state and needs human-led review before repair",
        status: RuleStatus::Experimental,
        standard_section: "Ownership Boundaries",
        cap_key: None,
        confidence_policy: ConfidencePolicy::Medium,
    },
    RuleSpec {
        id: "HLT-045-GENERATED-ZONE-GOVERNANCE",
        name: "Hand-edit inside a declared generated zone",
        category: "governance",
        tlr: "Contracts/data",
        lane: "contract",
        docs_url: "agent/JANKURAI_STANDARD.md#generated-zones",
        owner_hint: "tools",
        evidence_kind: "contract-manifest",
        severity: "medium",
        repairable: true,
        repair_eligibility: RepairEligibility::AgentAssisted,
        repair_risk: RepairRisk::Medium,
        repair_reason:
            "generated-zone hand-edits should be re-derived from the source generator, not patched in place",
        status: RuleStatus::Experimental,
        standard_section: "Generated Zones",
        cap_key: None,
        confidence_policy: ConfidencePolicy::Medium,
    },
    RuleSpec {
        id: "HLT-046-UNNECESSARY-VARIETY",
        name: "Redundant variety where consistency is expected",
        category: "copy-code",
        tlr: "Maintainability entropy",
        lane: "copy-code",
        docs_url: "agent/JANKURAI_STANDARD.md#jankurai-pillar-variety-and-canonical-shape",
        owner_hint: "tools",
        evidence_kind: "repository-scan",
        severity: "medium",
        repairable: true,
        repair_eligibility: RepairEligibility::AgentAssisted,
        repair_risk: RepairRisk::Medium,
        repair_reason:
            "reconciling diverging same-name definitions into one canonical shape is scoped but needs review that callers still agree",
        status: RuleStatus::Experimental,
        standard_section: "Jankurai Pillar: Variety and Canonical Shape",
        cap_key: None,
        confidence_policy: ConfidencePolicy::Medium,
    },
    RuleSpec {
        id: "HLT-047-CANONICAL-README",
        name: "README drifts from the canonical agent-native shape",
        category: "context",
        tlr: "Context/setup",
        lane: "fast",
        docs_url: "agent/JANKURAI_STANDARD.md#jankurai-pillar-variety-and-canonical-shape",
        owner_hint: "standard",
        evidence_kind: "repository-scan",
        severity: "medium",
        repairable: true,
        repair_eligibility: RepairEligibility::AgentAssisted,
        repair_risk: RepairRisk::Low,
        repair_reason:
            "adding the missing README links, stack statement, badge, or quick-start is mechanical doc editing",
        status: RuleStatus::Experimental,
        standard_section: "Jankurai Pillar: Variety and Canonical Shape",
        cap_key: None,
        confidence_policy: ConfidencePolicy::Medium,
    },
    RuleSpec {
        id: "HLT-048-CANONICAL-CI-GAP",
        name: "CI drifts from the canonical local-parity shape",
        category: "context",
        tlr: "Context/setup",
        lane: "audit",
        docs_url: "agent/JANKURAI_STANDARD.md#jankurai-pillar-variety-and-canonical-shape",
        owner_hint: "ops",
        evidence_kind: "repository-scan",
        severity: "medium",
        repairable: true,
        repair_eligibility: RepairEligibility::AgentAssisted,
        repair_risk: RepairRisk::Medium,
        repair_reason:
            "moving inline CI steps into ops/ci/*.sh, pinning action SHAs, and adding a jankurai audit lane is mechanical but should be proven by a green run",
        status: RuleStatus::Experimental,
        standard_section: "Jankurai Pillar: Variety and Canonical Shape",
        cap_key: None,
        confidence_policy: ConfidencePolicy::Medium,
    },
];

pub fn all() -> &'static [RuleSpec] {
    RULES
}

pub fn lookup(rule_id: &str) -> Option<RuleSpec> {
    RULES.iter().copied().find(|rule| rule.id == rule_id)
}

pub fn docs_for_rule_id(rule_id: &str) -> Option<&'static str> {
    lookup(rule_id).map(|rule| rule.docs_url)
}
