//! Embed the repo's JSON schemas into the binary at compile time.
//!
//! Historically schemas were read from `env!("CARGO_MANIFEST_DIR")/../../schemas` at *runtime*,
//! which baked the build-time directory into the binary. Once the binary was installed (or built in
//! an ephemeral sandbox) that directory no longer existed, so every schema load crashed with
//! `No such file or directory`. Embedding the schemas makes the binary relocation-independent: the
//! generated `EMBEDDED_SCHEMAS` table is `include_str!`-ed straight into the executable.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let schemas_dir = Path::new(&manifest)
        .join("..")
        .join("..")
        .join("schemas")
        .canonicalize()
        .expect("resolve schemas dir");
    println!("cargo:rerun-if-changed={}", schemas_dir.display());

    let mut entries: Vec<(String, String)> = Vec::new();
    for dent in fs::read_dir(&schemas_dir).expect("read schemas dir") {
        let path = dent.expect("schemas dir entry").path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let name = path
            .file_name()
            .and_then(|n| n.to_str())
            .expect("schema file name")
            .to_string();
        let abs = path.canonicalize().expect("canonicalize schema path");
        println!("cargo:rerun-if-changed={}", abs.display());
        entries.push((name, abs.to_string_lossy().into_owned()));
    }
    // Deterministic order so the generated table is stable across builds.
    entries.sort();

    let mut out = String::from(
        "// @generated by build.rs — embedded JSON schemas (relocation-independent).\n\
         pub static EMBEDDED_SCHEMAS: &[(&str, &str)] = &[\n",
    );
    for (name, abs) in &entries {
        out.push_str(&format!("    ({name:?}, include_str!({abs:?})),\n"));
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("schemas_embed.rs");
    fs::write(&dest, out).expect("write schemas_embed.rs");
}
